# Generated by Django 4.2.7 on 2026-07-02 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('blurb', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('gauge_type', models.CharField(blank=True, max_length=100)),
                ('thread_size', models.CharField(blank=True, max_length=100)),
                ('standard', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('summary', models.CharField(blank=True, help_text='One-line summary for cards', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('thread_size', models.CharField(blank=True, help_text='e.g. M14×1.5', max_length=60)),
                ('thread_class', models.CharField(blank=True, help_text='e.g. 6G, 6g, L1', max_length=20)),
                ('standard', models.CharField(choices=[('IS', 'IS (Indian Standard)'), ('ISO', 'ISO'), ('BS', 'BS (British Standard)'), ('ASME', 'ASME (American)'), ('DIN', 'DIN (German)'), ('CUSTOM', 'Custom / Non-Standard')], default='IS', max_length=10)),
                ('standard_ref', models.CharField(blank=True, help_text='e.g. IS 1880 / ISO 1502', max_length=100)),
                ('go_id', models.CharField(blank=True, help_text='e.g. R2509/12', max_length=50)),
                ('nogo_id', models.CharField(blank=True, help_text='e.g. R2509/13', max_length=50)),
                ('material', models.CharField(default='OHNS / HCHCr tool steel', max_length=100)),
                ('hardness', models.CharField(default='58–62 HRC', max_length=50)),
                ('finish', models.CharField(default='Precision ground & lapped', max_length=100)),
                ('calibration', models.CharField(default='Calibrated on Octagon LMM 400', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_key', models.CharField(blank=True, help_text='Bundled frontend asset key, e.g. m14x1_5', max_length=40)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='gauges.category')),
            ],
            options={
                'ordering': ['category__order', 'name'],
            },
        ),
    ]
